"""Stage 12 -- full deliverable QA: rebuild dashboard + poster from scratch.

Why this exists (2026-07-10): the previous dashboard/poster (archived under
dashboard/_archive, poster/_archive) predated the entire scope restructuring (still
referenced the dropped district-vulnerability index, Moran's I/Gi* spatial clustering, and
regional fertility clustering) AND independently violated this project's own standing
technical spec: 1.2 MB each (hard ceiling is 60 KB), with embedded base64 raster images
(spec requires vanilla JS + inline SVG only, no external JS, no base64 images). Both
problems are fixed by rebuilding from scratch against the current, narrowed manuscript
scope (21 national indicators, no spatial/district content) using only inline SVG charts
generated here and vanilla JS for the sortable table -- no matplotlib PNG/base64 anywhere
in the shipped HTML.

2026-07-11 update #1: restyled to adopt the project's bespoke visual design language
(gradient masthead/header, accent-bar KPI cards, numbered section badges, dark-mode
support, gold takeaway callout).

2026-07-11 update #2 (same day): user asked to match the *actual, currently-shipped*
dashboards/posters of the two most recent sibling projects (21. Spatial NCD Burden
Determinants Ghana, 22. Alcohol NCD Suicidality Ghana), QR code included, not just the
generic `_system/bespoke` templates. Those live files are themselves ~1.2 MB (full ECharts
library + a base64 QR PNG generated by the Node `bespoke_gen.js` pipeline), which still
conflicts with this project's own <60 KB / vanilla-JS-only ceiling -- so the exact CSS
tokens, class names, and print-layout units (`.wrap`/`header.top`/`.summary`/`.kpis`/
`.grid`+`.spanN`/`.foot` for the dashboard; `.ph`/`.hook`/`.bignums`/`.body`+`.col`+
`.block h2 .n`/`.takeaway`/`.limBox`/`.pf`+`.qr` for the A0-print poster, all in real `mm`
units) were extracted byte-for-byte from the live sibling HTML files and ported here,
while the QR code itself is generated as a real, scannable inline SVG (via the `qrcode`
package, SvgPathImage factory) instead of a base64 PNG -- satisfying "do not leave out the
QR code" without reintroducing the base64-raster-image violation the original dashboard
rebuild (2026-07-10, see above) existed specifically to fix. Chart rendering stays inline
SVG (trend_svg, margin_svg, unchanged); data-encoding colours stay the Okabe-Ito palette
already used in the manuscript figures -- only chrome (headers, cards, footers, badges)
uses the sibling projects' ink/primary/gold tokens, so the two colour systems never fight
over the same visual channel.
"""
import pandas as pd
import numpy as np
import datetime
import io
import re
import qrcode
import qrcode.image.svg
BUILD_DATE = datetime.date.today().isoformat()

ROOT = r"C:\Users\VGhanem\Documents\Claude\Projects\Public Health & Epidemiology Research Skills\23. Disease Burden Forecasting Ghana"
REPO_URL = "https://github.com/valentineghanem-bit/disease-burden-forecasting-ghana"

fc = pd.read_csv(ROOT + r"\outputs\data\national_forecasts_2030.csv")
panel = pd.read_csv(ROOT + r"\data\processed\national_panel.csv")
margin = pd.read_csv(ROOT + r"\outputs\data\aicc_margin_vs_uniform111.csv").sort_values("delta_aicc")

# ---------- Palette (Okabe-Ito colourblind-safe, matches manuscript figures) ----------
BLUE = "#0072b2"
GREEN = "#009e73"
PINK = "#cc79a7"
ORANGE = "#d55e00"
GREY = "#555555"
BG = "#ffffff"

# ---------- Chrome tokens, extracted verbatim from the two most recent sibling projects'
# shipped dashboard/poster CSS (21. Spatial NCD Burden Determinants Ghana,
# 22. Alcohol NCD Suicidality Ghana) -- never used for data encoding, only chrome. ----------
INK = "#16222e"
MUTED = "#5b6b7b"
PRIMARY = "#1a5276"
PRIMARY2 = "#3a93cf"
GOLD = "#d4a017"

# Dashboard-specific tokens (siblings' dashboard :root differs slightly from their poster :root)
D_BG = "#eef2f7"
D_PANEL = "#ffffff"
D_INK = "#1b2733"
D_MUTED = "#6b7a8d"
D_LINE = "#e3e9f0"
D_CTL = "#f4f7fb"
D_SHADOW = "0 1px 3px rgba(16,42,67,.08),0 8px 24px rgba(16,42,67,.06)"
D_BG_DARK = "#0e1620"
D_PANEL_DARK = "#16202c"
D_INK_DARK = "#e7eef6"
D_MUTED_DARK = "#90a2b6"
D_LINE_DARK = "#243443"
D_CTL_DARK = "#1c2735"
D_PRIMARY_DARK = "#4a90d9"
D_PRIMARY2_DARK = "#67b0ee"
D_SHADOW_DARK = "0 1px 3px rgba(0,0,0,.4),0 10px 30px rgba(0,0,0,.35)"

LABELS = {
    "life_expectancy_birth_yrs_who": "Life expectancy (WHO-GHO), yrs",
    "hale_birth_yrs": "Healthy life expectancy, yrs",
    "u5mr_who": "Under-five mortality, per 1,000",
    "ncd_premature_pct": "NCD premature mortality, %",
    "ncd_3070_probability_pct": "NCD 30-70 death probability, %",
    "total_ncd_deaths": "Total NCD deaths, n",
    "suicide_rate_crude_who": "Suicide rate, crude (WHO-GHO)",
    "suicide_rate_agestd_who": "Suicide rate, age-std. (WHO-GHO)",
    "tb_incidence_per100k": "Tuberculosis incidence, per 100,000",
    "hiv_new_infections_n": "HIV new infections, n",
    "hiv_new_infections_per1000": "HIV new infections, per 1,000",
    "malaria_incidence_per1000atrisk": "Malaria incidence, per 1,000 at risk",
    "oop_pct_che": "Out-of-pocket exp., % of CHE",
    "oop_percapita_usd": "Out-of-pocket exp. per capita, USD",
    "che_pct_gdp": "Current health exp., % GDP (WHO-GHO)",
    "che_percapita_usd": "Current health exp. per capita, USD",
    "life_expectancy_birth_yrs_wb": "Life expectancy (World Bank), yrs",
    "suicide_rate_wb": "Suicide rate (World Bank)",
    "che_pct_gdp_wb": "Current health exp., % GDP (World Bank)",
    "tfr_national_wb": "Total fertility rate (World Bank)",
    "pm25_exposure_wb": "PM2.5 exposure (World Bank)",
}
ROW_ORDER = list(LABELS.keys())

def esc(s):
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

# ---------- Inline SVG QR code (real, scannable, generated at build time -- no external
# CDN/API call at render time, and no base64 raster image, matching this project's own
# vanilla-JS/inline-SVG-only spec while still shipping a working QR per sibling projects). ----------
def qr_svg(data, fill=INK):
    img = qrcode.make(data, image_factory=qrcode.image.svg.SvgPathImage, box_size=10, border=2)
    buf = io.BytesIO()
    img.save(buf)
    svg = buf.getvalue().decode("utf-8")
    svg = re.sub(r"<\?xml[^>]*\?>\n?", "", svg)
    svg = re.sub(r'width="[\d.]+mm" height="[\d.]+mm" ', "", svg)
    svg = svg.replace('fill="#000000"', f'fill="{fill}"')
    return svg

QR_SVG = qr_svg(REPO_URL)

# ---------- SVG chart 1: national trend, 3 small multiples (U5MR, TB, Malaria) ----------
def trend_svg():
    series_defs = [
        ("u5mr_who", "Under-five mortality (per 1,000 live births)", BLUE, 0, 0),
        ("tb_incidence_per100k", "Tuberculosis incidence (per 100,000)", GREEN, 1, 0),
        ("malaria_incidence_per1000atrisk", "Malaria incidence (per 1,000 at risk)", PINK, 2, 0),
    ]
    W, H = 720, 230
    panel_w, gap = 220, 30
    svg_parts = [f'<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" font-family="Arial, sans-serif">']
    svg_parts.append(f'<rect width="{W}" height="{H}" fill="{BG}"/>')
    for i, (col, title, color, cx, cy) in enumerate(series_defs):
        ox = 10 + i * (panel_w + gap)
        oy = 20
        pw, ph = panel_w, 150
        s = panel[["year", col]].dropna().sort_values("year")
        years = s["year"].values
        vals = s[col].values
        row = fc[fc["indicator"] == col].iloc[0]
        last_year = years[-1]
        last_val = vals[-1]
        fc2030 = row["arima_2030"]
        all_y = list(vals) + [fc2030]
        ymin, ymax = min(all_y) * 0.92, max(all_y) * 1.08
        xmin, xmax = years[0], 2030
        def px(x): return ox + (x - xmin) / (xmax - xmin) * pw
        def py(y): return oy + ph - (y - ymin) / (ymax - ymin) * ph
        pts = " ".join(f"{px(x):.1f},{py(y):.1f}" for x, y in zip(years, vals))
        svg_parts.append(f'<text x="{ox}" y="{oy-6}" font-size="11" font-weight="bold" fill="#222">{esc(title)}</text>')
        svg_parts.append(f'<polyline points="{pts}" fill="none" stroke="{color}" stroke-width="1.6"/>')
        svg_parts.append(f'<line x1="{px(last_year):.1f}" y1="{py(last_val):.1f}" x2="{px(2030):.1f}" y2="{py(fc2030):.1f}" '
                          f'stroke="{color}" stroke-width="1.6" stroke-dasharray="4,3"/>')
        svg_parts.append(f'<circle cx="{px(2030):.1f}" cy="{py(fc2030):.1f}" r="3" fill="{color}"/>')
        svg_parts.append(f'<text x="{px(2030)-4:.1f}" y="{py(fc2030)-8:.1f}" font-size="10" text-anchor="end" fill="{color}">{fc2030:,.1f}</text>')
        svg_parts.append(f'<line x1="{ox}" y1="{oy+ph}" x2="{ox+pw}" y2="{oy+ph}" stroke="#ccc" stroke-width="1"/>')
        svg_parts.append(f'<text x="{ox}" y="{oy+ph+14}" font-size="9" fill="#666">{int(years[0])}</text>')
        svg_parts.append(f'<text x="{ox+pw}" y="{oy+ph+14}" font-size="9" text-anchor="end" fill="#666">2030</text>')
    svg_parts.append("</svg>")
    return "".join(svg_parts)

# ---------- SVG chart 2: AICc margin, all 21 series, sorted, horizontal bars ----------
def margin_svg():
    W, H = 720, 460
    left_pad, right_pad, top_pad, bot_pad = 210, 40, 10, 25
    pw = W - left_pad - right_pad
    ph = H - top_pad - bot_pad
    n = len(margin)
    bar_h = ph / n * 0.7
    gap_h = ph / n
    maxv = margin["delta_aicc"].max()
    minv = min(0, margin["delta_aicc"].min())
    def px(v): return left_pad + (v - minv) / (maxv - minv) * pw
    svg = [f'<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" font-family="Arial, sans-serif">']
    svg.append(f'<rect width="{W}" height="{H}" fill="{BG}"/>')
    thresh_x = px(2)
    svg.append(f'<line x1="{thresh_x:.1f}" y1="{top_pad}" x2="{thresh_x:.1f}" y2="{top_pad+ph}" stroke="#333" stroke-width="1" stroke-dasharray="3,2"/>')
    svg.append(f'<text x="{thresh_x+3:.1f}" y="{top_pad+10}" font-size="9" fill="#333">near-tie threshold (2)</text>')
    for i, (_, r) in enumerate(margin.iterrows()):
        y = top_pad + i * gap_h + (gap_h - bar_h) / 2
        color = BLUE if r["near_tie"] else ORANGE
        x0 = px(min(0, r["delta_aicc"]))
        w = abs(px(r["delta_aicc"]) - px(0))
        svg.append(f'<rect x="{x0:.1f}" y="{y:.1f}" width="{max(w,1):.1f}" height="{bar_h:.1f}" fill="{color}"/>')
        label = LABELS[r["indicator"]]
        svg.append(f'<text x="{left_pad-6}" y="{y+bar_h/2+3:.1f}" font-size="9" text-anchor="end" fill="#222">{esc(label)}</text>')
    svg.append(f'<text x="{left_pad}" y="{H-6}" font-size="10" fill="#444">AICc difference vs. uniform ARIMA(1,1,1)</text>')
    legend_y = top_pad + 8
    svg.append(f'<rect x="{W-right_pad-14}" y="{legend_y}" width="10" height="10" fill="{BLUE}"/>')
    svg.append(f'<text x="{W-right_pad-18}" y="{legend_y+9}" font-size="8" text-anchor="end" fill="#222">Near-tie</text>')
    svg.append(f'<rect x="{W-right_pad-14}" y="{legend_y+14}" width="10" height="10" fill="{ORANGE}"/>')
    svg.append(f'<text x="{W-right_pad-18}" y="{legend_y+23}" font-size="8" text-anchor="end" fill="#222">Decisive</text>')
    svg.append("</svg>")
    return "".join(svg)

TREND_SVG = trend_svg()
MARGIN_SVG = margin_svg()

# ---------- shared table HTML (Table 1 content) ----------
def table_rows_html():
    rows = []
    for ind in ROW_ORDER:
        d = fc[fc["indicator"] == ind].iloc[0]
        is_count = ind in ("total_ncd_deaths", "hiv_new_infections_n")
        conf = "Standard" if d["confidence"].strip().lower() == "standard" else "Low"
        def f(v):
            return f"{v:,.0f}" if is_count else f"{v:,.2f}"
        rows.append(
            f'<tr><td>{esc(LABELS[ind])}</td><td>{int(d["n_obs"])}</td><td>{int(d["last_year"])}</td>'
            f'<td>{esc(d["arima_order"])}</td><td>{f(d["last_value"])}</td><td>{f(d["arima_2030"])}</td>'
            f'<td>{f(d["arima_ci_low"])}–{f(d["arima_ci_high"])}</td><td>{f(d["ets_2030"])}</td>'
            f'<td><span class="conftag {"std" if conf=="Standard" else "low"}">{conf}</span></td></tr>'
        )
    return "".join(rows)

TABLE_ROWS = table_rows_html()
print(f"TREND_SVG size: {len(TREND_SVG)/1024:.1f} KB | MARGIN_SVG size: {len(MARGIN_SVG)/1024:.1f} KB | TABLE_ROWS size: {len(TABLE_ROWS)/1024:.1f} KB | QR_SVG size: {len(QR_SVG)/1024:.1f} KB")

n_standard = (fc["confidence"].str.strip().str.lower() == "standard").sum()
n_low = len(fc) - n_standard
low_rows = fc[fc["confidence"].str.strip().str.lower() != "standard"]
low_n_min, low_n_max = int(low_rows["n_obs"].min()), int(low_rows["n_obs"].max())
malaria_row = fc[fc["indicator"] == "malaria_incidence_per1000atrisk"].iloc[0]
u5mr_row = fc[fc["indicator"] == "u5mr_who"].iloc[0]
tb_row = fc[fc["indicator"] == "tb_incidence_per100k"].iloc[0]

sens = pd.read_csv(ROOT + r"\outputs\data\arima_order_sensitivity.csv")
n_matched_111 = (sens["matches_111"].astype(str).str.strip().str.lower() == "true").sum()
n_near_tie = (margin["near_tie"].astype(str).str.strip().str.lower() == "true").sum()

# Structural-break sensitivity (Table 5) -- read live, not hardcoded, so the dashboard/poster
# can never silently drift from the manuscript's own verified structural-break numbers.
sb = pd.read_csv(ROOT + r"\outputs\data\structural_break_sensitivity.csv")
sb_malaria = sb[sb["indicator"] == "malaria_incidence_per1000atrisk"].iloc[0]
sb_lifeexp_wb = sb[sb["indicator"] == "life_expectancy_birth_yrs_wb"].iloc[0]
n_covid_testable = (sb["covid_2020_testable"].astype(str).str.strip().str.lower() == "true").sum()
n_covid_decisive = (sb.loc[sb["covid_2020_testable"].astype(str).str.strip().str.lower() == "true", "covid_2020_delta_aicc"].astype(float) > 2).sum()
n_currency_testable = (sb["currency_2022_testable"].astype(str).str.strip().str.lower() == "true").sum()
n_currency_decisive = (sb.loc[sb["currency_2022_testable"].astype(str).str.strip().str.lower() == "true", "currency_2022_delta_aicc"].astype(float) > 2).sum()
n_break_decisive_total = int(n_covid_decisive + n_currency_decisive)
n_break_testable_total = int(n_covid_testable + n_currency_testable)

# Pre-correction (raw-scale, uniform ARIMA(1,1,1)) malaria baseline -- recomputed live, not
# hardcoded, so this figure can never silently drift from the manuscript's own verified number.
# Three-way breakdown (2026-07-11 council fix): the ARIMA-vs-ETS gap narrowing is driven mostly
# by fitting SCALE (raw -> log), not by order selection -- isolating order selection alone
# (holding log scale fixed) actually re-opens some of the gap. See manuscript Results/Discussion
# for the full disentangled explanation; these three numbers must stay in lockstep with it.
import warnings
warnings.filterwarnings("ignore")
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.holtwinters import ExponentialSmoothing
_mal = panel[["year", "malaria_incidence_per1000atrisk"]].dropna().sort_values("year")
_y = _mal["malaria_incidence_per1000atrisk"].values
_steps = 2030 - int(_mal["year"].max())
_arima_raw_111 = ARIMA(_y, order=(1, 1, 1)).fit().get_forecast(steps=_steps).predicted_mean[-1]
_ets_raw = ExponentialSmoothing(_y, trend="add", damped_trend=True).fit().forecast(_steps)[-1]
malaria_gap_naive_pct = abs(_arima_raw_111 - _ets_raw) / _ets_raw * 100
_order_comp = pd.read_csv(ROOT + r"\outputs\data\forecast_order_comparison.csv")
_malaria_fixed_111_logscale = _order_comp.loc[_order_comp["indicator"] == "malaria_incidence_per1000atrisk", "fixed_111_2030"].iloc[0]
malaria_gap_logscale_fixed_pct = abs(_malaria_fixed_111_logscale - malaria_row["ets_2030"]) / malaria_row["ets_2030"] * 100
malaria_gap_final_pct = abs(malaria_row["arima_2030"] - malaria_row["ets_2030"]) / malaria_row["ets_2030"] * 100

# ============================================================
# DASHBOARD -- CSS tokens/classes ported verbatim from the sibling projects' shipped
# dashboards (21. Spatial NCD Burden Determinants Ghana, 22. Alcohol NCD Suicidality Ghana):
# .wrap / header.top (.meta, .brand) / .summary / .kpis+.kpi / .grid+.card+.spanN / .foot.
# Spatial-only toolbar controls (region selector, LISA chips, map zoom, threshold slider) are
# not applicable to this project's national time-series scope and are replaced with the
# equivalent project-appropriate controls (filter, sort, export, reset, theme).
# ============================================================
DASHBOARD_HTML = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Ghana Burden Forecasting 2030 — Dashboard &amp; Source-Provenance Audit</title>
<style>
:root{{--bg:{D_BG};--panel:{D_PANEL};--ink:{D_INK};--muted:{D_MUTED};--line:{D_LINE};--primary:{PRIMARY};--primary2:{PRIMARY2};
 --shadow:{D_SHADOW};--ctl:{D_CTL};--gold:{GOLD}}}
html[data-theme=dark]{{--bg:{D_BG_DARK};--panel:{D_PANEL_DARK};--ink:{D_INK_DARK};--muted:{D_MUTED_DARK};--line:{D_LINE_DARK};--primary:{D_PRIMARY_DARK};--primary2:{D_PRIMARY2_DARK};--ctl:{D_CTL_DARK};--shadow:{D_SHADOW_DARK}}}
@media (prefers-reduced-motion: reduce) {{ *,*::before,*::after {{ animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important }} }}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--bg);color:var(--ink);font-family:'Inter',system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;-webkit-font-smoothing:antialiased;transition:background .25s,color .25s}}
.wrap{{max-width:1280px;margin:0 auto;padding:16px 20px 48px}}
header.top{{display:flex;flex-wrap:wrap;gap:14px;align-items:center;justify-content:space-between;background:linear-gradient(120deg,var(--primary),var(--primary2));color:#fff;border-radius:16px;padding:16px 22px;box-shadow:var(--shadow)}}
header.top h1{{margin:0;font-size:1.26rem;font-weight:800;letter-spacing:-.01em;max-width:820px}}
header.top .meta{{font-size:.76rem;opacity:.92;margin-top:3px}}
.brand{{font-size:.72rem;font-weight:800;letter-spacing:.04em;background:rgba(255,255,255,.16);padding:6px 12px;border-radius:20px;white-space:nowrap;align-self:center}}
.toolbar{{display:flex;flex-wrap:wrap;gap:14px 18px;align-items:flex-end;background:var(--panel);border:1px solid var(--line);border-radius:14px;box-shadow:var(--shadow);padding:12px 16px;margin:14px 0}}
.ctl{{display:flex;flex-direction:column;gap:5px}}
.ctl>label{{font-size:.66rem;font-weight:800;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}}
.ctl input#search{{font:inherit;font-size:.78rem;border:1px solid var(--line);background:var(--ctl);color:var(--ink);border-radius:8px;padding:7px 10px;width:220px}}
.spacer{{flex:1}}
.btn{{border:1px solid var(--line);background:var(--ctl);color:var(--ink);font:inherit;font-size:.76rem;font-weight:700;padding:8px 12px;border-radius:9px;cursor:pointer}}
.btn:hover{{background:var(--primary);color:#fff;border-color:var(--primary)}}
.btn:focus-visible,.ctl input#search:focus-visible{{outline:2px solid var(--primary2);outline-offset:1px}}
.summary{{display:flex;flex-wrap:wrap;gap:10px 26px;align-items:center;background:linear-gradient(120deg,rgba(26,82,118,.08),rgba(58,147,207,.04));border:1px solid var(--line);border-radius:12px;padding:10px 16px;margin-bottom:14px;font-size:.8rem}}
.summary .s{{display:flex;flex-direction:column}}
.summary .s b{{font-size:1.05rem;font-weight:800;color:var(--primary);line-height:1.1}}
.summary .s span{{font-size:.66rem;color:var(--muted);text-transform:uppercase;letter-spacing:.04em}}
.summary .sel{{margin-left:auto;font-size:.74rem;color:var(--muted)}}
.summary .sel b{{color:var(--ink)}}
.kpis{{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px;margin:0 0 14px}}
.kpi{{background:var(--panel);border-radius:14px;padding:14px 15px;box-shadow:var(--shadow);border:1px solid var(--line);position:relative;overflow:hidden}}
.kpi::before{{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--primary)}}
.kpi .v{{font-size:1.5rem;font-weight:800;letter-spacing:-.02em}}
.kpi .l{{font-size:.72rem;font-weight:700;margin-top:2px}}
.kpi .s{{font-size:.66rem;color:var(--muted);margin-top:3px}}
.grid{{display:grid;grid-template-columns:repeat(12,1fr);gap:13px}}
.card{{background:var(--panel);border-radius:14px;box-shadow:var(--shadow);border:1px solid var(--line);padding:13px 15px 8px}}
.card h3{{margin:0 0 1px;font-size:.84rem;font-weight:800}}
.card .cap{{font-size:.68rem;color:var(--muted);margin:0 0 8px}}
.span6{{grid-column:span 6}}.span12{{grid-column:span 12}}
table{{width:100%;border-collapse:collapse;font-size:.82rem}}
th,td{{padding:6px 8px;text-align:left;border-bottom:1px solid var(--line)}}
th{{cursor:pointer;user-select:none;background:var(--bg);position:sticky;top:0;white-space:nowrap}}
th:hover{{color:var(--primary)}}
td:nth-child(2),td:nth-child(3),td:nth-child(5),td:nth-child(6),td:nth-child(7),td:nth-child(8){{text-align:right;font-variant-numeric:tabular-nums}}
.conftag{{padding:2px 8px;border-radius:10px;font-size:.72rem;font-weight:600}}
.conftag.std{{background:#e3f2ec;color:{GREEN}}}
.conftag.low{{background:#fdecec;color:#b3261e}}
.table-wrap{{max-height:520px;overflow:auto;border:1px solid var(--line);border-radius:8px}}
.foot{{margin-top:20px;font-size:.7rem;color:var(--muted);line-height:1.5}}
.foot a{{color:var(--primary)}}
@media(max-width:1100px){{.kpis{{grid-template-columns:repeat(2,1fr)}}.span6{{grid-column:span 12}}}}
</style>
</head>
<body>
<div class="wrap">
<header class="top">
  <div><h1>A Reproducible Workflow and Source-Provenance Audit for Forecasting Short National Health-Indicator Panels: A Worked Example from Ghana</h1>
  <div class="meta">25 indicators assembled, 21 forecastable · 6 documented data-integrity corrections · last rebuilt {BUILD_DATE}</div></div>
  <div class="brand">HI-EI Dashboard</div>
</header>
<div class="toolbar">
  <div class="ctl"><label for="search">Filter indicator</label><input id="search" type="text" placeholder="Type to filter…" onkeyup="filterTable()"></div>
  <div class="spacer"></div>
  <div class="ctl"><label>&nbsp;</label><div style="display:flex;gap:7px">
    <button class="btn" onclick="resetView()">↺ Reset</button>
    <button class="btn" onclick="toggleTheme()">◐ Theme</button>
    <button class="btn" onclick="exportCSV()">⬇ CSV</button>
  </div></div>
</div>
<div class="summary">
  <div class="s"><b>25</b><span>Indicators assembled</span></div>
  <div class="s"><b>21</b><span>Forecastable (≥15y)</span></div>
  <div class="s"><b>9</b><span>Public-domain sources</span></div>
  <div class="s"><b>6</b><span>Data-integrity corrections</span></div>
  <div class="sel">STROBE reporting · <b>MIT-licensed code</b></div>
</div>
<div class="kpis">
  <div class="kpi"><div class="v">6</div><div class="l">Documented corrections</div><div class="s">source-provenance pitfalls fixed (Table 1)</div></div>
  <div class="kpi"><div class="v">{u5mr_row['arima_2030']:.1f}</div><div class="l">Under-five mortality, 2030</div><div class="s">per 1,000 live births · SDG 3.2 target: 25</div></div>
  <div class="kpi"><div class="v">{n_near_tie} / 21</div><div class="l">Order-selection near-ties</div><div class="s">uniform ARIMA(1,1,1) not decisively rejected</div></div>
  <div class="kpi"><div class="v">malaria, WB life exp.</div><div class="l">Structural breaks found</div><div class="s">decisive: {n_covid_decisive} of {n_covid_testable} testable (COVID-2020), {n_currency_decisive} of {n_currency_testable} (currency-2022)</div></div>
  <div class="kpi"><div class="v">ARIMA + ETS</div><div class="l">Forecasting method</div><div class="s">LSTM did not outperform (walk-forward validated)</div></div>
</div>

<div class="grid">
  <div class="card span12">
    <h3>Source-provenance audit: six silent data-integrity pitfalls (Table 1)</h3>
    <p class="cap">The reusable contribution of this analysis is the workflow and these named pitfalls, not the Ghana-specific forecasts below. Each corrects a WHO GHO/World Bank export issue that produces output that looks correct and is not.</p>
    <table>
      <thead><tr><th>Source file / series</th><th>Pitfall</th><th>Correction applied</th></tr></thead>
      <tbody>
        <tr><td>All WHO GHO/GHE exports</td><td>Leading hashtag (HXL) metadata row breaks numeric coercion</td><td>Drop HXL row before numeric coercion</td></tr>
        <tr><td>Under-five mortality rate</td><td>Wealth-quintile stratification presents as year-level duplication</td><td>Retained national-total series; did not average across quintiles</td></tr>
        <tr><td>Air-pollution indicators (2 series)</td><td>Cause-of-death sub-category stratification presents as year-level duplication</td><td>Retained per-year maximum (all-causes total), not sum or average</td></tr>
        <tr><td>Crude suicide rate, 2021</td><td>Recurring WHO GHO export anomaly (36 rows vs. expected 3)</td><td>Retained only confidence-interval-bearing rows</td></tr>
        <tr><td>WHS compendium + consolidated GHO export</td><td>Near-total re-exports of the disease-specific source files</td><td>Used as internal consistency checks only, never merged as new observations</td></tr>
        <tr><td>Current health exp. (% GDP): WHO-GHO vs. World Bank</td><td>Two &quot;sources&quot; numerically identical to several decimal places</td><td>Flagged non-independent; excluded from cross-source validation claims</td></tr>
      </tbody>
    </table>
  </div>
  <div class="card span6">
    <h3>National indicator trends and 2030 forecasts</h3>
    <p class="cap">Dashed segment: ARIMA point forecast to 2030. Full methodology in the manuscript (Figure 1).</p>
    {TREND_SVG}
  </div>
  <div class="card span6">
    <h3>Order-selection sensitivity, all 21 series</h3>
    <p class="cap">AICc difference between each series' own selected order and a uniform ARIMA(1,1,1) refit. Only {n_matched_111} of 21 series matched the uniform order exactly; {n_near_tie} of 21 were statistical near-ties (manuscript Table 4).</p>
    {MARGIN_SVG}
  </div>
  <div class="card span12">
    <h3>Structural-break sensitivity</h3>
    <p class="cap">Testing rather than assuming away the 2020 COVID-19 and 2022 Ghana currency-crisis breaks: a decisive currency-crisis break shifts the malaria 2030 forecast by a further {sb_malaria['currency_2022_pct_change_2030']:+.1f}% (larger than the order-selection effect above), and a decisive break at both candidate dates is found for the World Bank life-expectancy series -- a plausible partial explanation for its divergence from the WHO-GHO life-expectancy series, not a resolved causal account. Most series' break tests are underpowered on 2–5 post-break observations (manuscript Table 5).</p>
  </div>
  <div class="card span12">
    <h3>Full forecast table</h3>
    <div class="table-wrap">
    <table id="fctable">
      <thead><tr>
        <th onclick="sortTable(0)">Indicator</th>
        <th onclick="sortTable(1)">n</th>
        <th onclick="sortTable(2)">Last year</th>
        <th onclick="sortTable(3)">ARIMA order</th>
        <th onclick="sortTable(4)">Last value</th>
        <th onclick="sortTable(5)">ARIMA 2030</th>
        <th>95% CI</th>
        <th onclick="sortTable(7)">ETS 2030</th>
        <th onclick="sortTable(8)">Confidence</th>
      </tr></thead>
      <tbody>{TABLE_ROWS}</tbody>
    </table>
    </div>
  </div>
</div>
<div class="foot">
  Source data: WHO Global Health Observatory / Global Health Estimates and World Bank World Development Indicators (public-domain, aggregate, de-identified).
  Methodology, full citations, and limitations: see manuscript. Repository:
  <a href="https://github.com/valentineghanem-bit/disease-burden-forecasting-ghana" target="_blank" rel="noopener">disease-burden-forecasting-ghana</a>.
</div>
</div>
<script>
(function() {{
  if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {{
    document.documentElement.setAttribute('data-theme', 'dark');
  }}
}})();
function toggleTheme() {{
  const html = document.documentElement;
  html.setAttribute('data-theme', html.getAttribute('data-theme') === 'dark' ? 'light' : 'dark');
}}
function filterTable() {{
  const q = document.getElementById('search').value.toLowerCase();
  document.querySelectorAll('#fctable tbody tr').forEach(function(row) {{
    row.style.display = row.cells[0].textContent.toLowerCase().includes(q) ? '' : 'none';
  }});
}}
let sortDir = {{}};
function sortTable(colIdx) {{
  const tbody = document.querySelector('#fctable tbody');
  const rows = Array.from(tbody.querySelectorAll('tr'));
  const dir = sortDir[colIdx] = !sortDir[colIdx];
  rows.sort(function(a, b) {{
    let x = a.cells[colIdx].textContent.trim();
    let y = b.cells[colIdx].textContent.trim();
    const xn = parseFloat(x.replace(/,/g, '')), yn = parseFloat(y.replace(/,/g, ''));
    if (!isNaN(xn) && !isNaN(yn)) {{ x = xn; y = yn; }}
    if (x < y) return dir ? -1 : 1;
    if (x > y) return dir ? 1 : -1;
    return 0;
  }});
  rows.forEach(function(r) {{ tbody.appendChild(r); }});
}}
const ORIGINAL_ROWS = document.querySelector('#fctable tbody').innerHTML;
function resetView() {{
  document.getElementById('search').value = '';
  document.querySelector('#fctable tbody').innerHTML = ORIGINAL_ROWS;
  sortDir = {{}};
}}
function exportCSV() {{
  const headerCells = Array.from(document.querySelectorAll('#fctable thead tr:last-child th'));
  const header = headerCells.map(function(th) {{ return '"' + th.textContent.trim().replace(/"/g, '""') + '"'; }});
  const rows = Array.from(document.querySelectorAll('#fctable tbody tr')).filter(function(r) {{ return r.style.display !== 'none'; }});
  const lines = [header.join(',')];
  rows.forEach(function(row) {{
    const cells = Array.from(row.cells).map(function(td) {{ return '"' + td.textContent.trim().replace(/"/g, '""') + '"'; }});
    lines.push(cells.join(','));
  }});
  const blob = new Blob([lines.join('\\n')], {{ type: 'text/csv' }});
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = 'ghana_forecast_2030_table.csv';
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
}}
</script>
</body>
</html>
"""

with open(ROOT + r"\dashboard\Ghana_BurdenForecasting2030_Dashboard.html", "w", encoding="utf-8") as f:
    f.write(DASHBOARD_HTML)
print(f"Dashboard written: {len(DASHBOARD_HTML)/1024:.1f} KB")

# ============================================================
# POSTER -- A0 print (841x1189mm), CSS tokens/classes ported verbatim from the sibling
# projects' shipped posters: .ph masthead / .hook / .bignums+.bn / .body+.col+.block h2 .n /
# .takeaway / .limBox / .pf+.qr footer. Two numbered columns (not three) to match the
# sibling 2-col print layout; Limitations gets its own full-width .limBox (not a numbered
# block) and Conclusion is folded into the sibling's ".takeaway / What it means" callout,
# mirroring the sibling information architecture rather than just its colours.
# ============================================================
POSTER_ROW_ORDER = ["u5mr_who", "tb_incidence_per100k", "malaria_incidence_per1000atrisk",
    "hiv_new_infections_per1000", "life_expectancy_birth_yrs_who", "life_expectancy_birth_yrs_wb",
    "tfr_national_wb", "oop_pct_che"]

def poster_table_rows():
    rows = []
    for ind in POSTER_ROW_ORDER:
        d = fc[fc["indicator"] == ind].iloc[0]
        is_count = ind in ("total_ncd_deaths", "hiv_new_infections_n")
        conf = "Standard" if d["confidence"].strip().lower() == "standard" else "Low"
        def f(v):
            return f"{v:,.0f}" if is_count else f"{v:,.1f}"
        rows.append(f'<tr><td>{esc(LABELS[ind])}</td><td>{f(d["last_value"])}</td><td>{f(d["arima_2030"])}</td>'
                     f'<td>{f(d["ets_2030"])}</td><td><span class="conftag {"std" if conf=="Standard" else "low"}">{conf}</span></td></tr>')
    return "".join(rows)

POSTER_TABLE_ROWS = poster_table_rows()

POSTER_HTML = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Ghana Burden Forecasting 2030 — Poster</title>
<style>
@page{{size:841mm 1189mm;margin:0}}
:root{{--ink:{INK};--muted:{MUTED};--primary:{PRIMARY};--primary2:{PRIMARY2};--gold:{GOLD};--paper:#fff;--soft:#f4f7fb;--line:#e2e9f1}}
*{{box-sizing:border-box}}
body{{margin:0;background:#7f8c9b;font-family:'Inter',system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:var(--ink)}}
.poster{{width:841mm;min-height:1189mm;margin:0 auto;background:var(--paper);display:flex;flex-direction:column}}
@media screen{{.poster{{box-shadow:0 8px 40px rgba(0,0,0,.35);margin:14px auto}}}}
.ph{{background:linear-gradient(120deg,var(--primary),var(--primary2));color:#fff;padding:34mm 30mm 24mm;position:relative;overflow:hidden}}
.ph::after{{content:"";position:absolute;right:-60mm;top:-60mm;width:180mm;height:180mm;border-radius:50%;background:rgba(255,255,255,.06)}}
.ph .kicker{{font-size:10mm;font-weight:800;letter-spacing:.06em;text-transform:uppercase;opacity:.85}}
.ph h1{{margin:6mm 0 4mm;font-size:19mm;line-height:1.12;font-weight:900;letter-spacing:-.01em;max-width:660mm}}
.ph .sub{{font-size:8mm;opacity:.95;max-width:640mm;line-height:1.3}}
.ph .auth{{margin-top:8mm;font-size:6.4mm;opacity:.9}}
.ph .badges{{position:absolute;right:30mm;top:30mm;text-align:right;font-size:5.6mm;line-height:1.7}}
.ph .pill{{display:inline-block;background:rgba(255,255,255,.18);padding:2mm 6mm;border-radius:30mm;font-weight:700;margin-left:3mm}}
.hook{{background:var(--ink);color:#fff;padding:14mm 30mm;font-size:10.5mm;font-weight:800;line-height:1.3}}
.bignums{{display:grid;grid-template-columns:repeat(4,1fr);background:var(--soft)}}
.bn{{padding:13mm 10mm;border-right:1px solid var(--line);text-align:center}}
.bn:last-child{{border-right:0}}
.bn .v{{font-size:20mm;font-weight:900;color:var(--primary);line-height:1;letter-spacing:-.02em}}
.bn .l{{font-size:6.2mm;font-weight:700;margin-top:4mm}}
.bn .s{{font-size:5mm;color:var(--muted);margin-top:2mm}}
.body{{flex:1;padding:18mm 30mm 8mm;display:grid;grid-template-columns:1fr 1fr;gap:16mm}}
.col{{display:flex;flex-direction:column;gap:14mm}}
.block h2{{font-size:9mm;font-weight:900;color:var(--primary);margin:0 0 2mm}}
.block h2 .n{{display:inline-block;width:13mm;height:13mm;line-height:13mm;text-align:center;background:var(--primary);color:#fff;border-radius:50%;font-size:7mm;margin-right:4mm;vertical-align:middle}}
.block p{{font-size:6.4mm;line-height:1.5;color:#2a3744;margin:2mm 0}}
.chart{{width:100%;background:var(--paper);border:1px solid var(--line);border-radius:4mm;padding:3mm}}
.cap{{font-size:5mm;color:var(--muted);margin-top:2mm}}
table{{width:100%;border-collapse:collapse;font-size:5.4mm}}
th,td{{padding:2mm 2.5mm;border-bottom:1px solid var(--line);text-align:left}}
td:nth-child(2),td:nth-child(3),td:nth-child(4){{text-align:right;font-variant-numeric:tabular-nums}}
th{{background:var(--soft)}}
.conftag{{padding:0.6mm 2.6mm;border-radius:3mm;font-size:4.6mm;font-weight:600}}
.conftag.std{{background:#e3f2ec;color:{GREEN}}}
.conftag.low{{background:#fdecec;color:#b3261e}}
.takeaway{{margin:0 30mm 8mm;background:var(--soft);border-left:6mm solid var(--gold);padding:10mm 12mm;border-radius:0 4mm 4mm 0}}
.takeaway h2{{color:var(--ink);font-size:7.5mm;font-weight:900;margin:0 0 2mm}}
.takeaway p{{font-size:7mm;font-weight:600;margin:0}}
.limBox{{margin:0 30mm 8mm;padding:8mm 12mm;border-radius:4mm;border:1px solid var(--line);background:var(--soft);color:var(--ink);font-size:5.4mm;line-height:1.5}}
.limBox h2{{font-size:6.4mm;font-weight:900;color:var(--primary);text-transform:uppercase;letter-spacing:.04em;margin:0 0 3mm}}
.pf{{background:linear-gradient(120deg,var(--primary),var(--primary2));color:#fff;padding:12mm 30mm;display:flex;justify-content:space-between;align-items:center;gap:12mm;font-size:5.4mm;line-height:1.5}}
.pf b{{font-weight:800}}
.qr{{width:40mm;height:40mm;min-width:40mm;background:#fff;border:3mm solid #fff;border-radius:3mm;box-sizing:border-box;flex:none}}
.qr svg{{width:100%;height:100%;display:block}}
@media print{{@page{{size:841mm 1189mm;margin:0}}html,body{{background:#fff!important}}.poster{{margin:0!important;box-shadow:none!important;width:841mm!important;height:1189mm!important;min-height:1189mm!important;max-height:1189mm!important;overflow:hidden!important}}}}
@media print{{body{{width:841mm;height:1189mm;overflow:hidden}}}}
</style>
</head>
<body>
<div class="poster">
  <div class="ph">
    <div class="badges">STROBE<span class="pill">MIT-licensed code</span><br/><span>Public-domain data</span></div>
    <div class="kicker">Reproducible workflow · Methods paper</div>
    <h1>A Reproducible Workflow and Source-Provenance Audit for Forecasting Short National Health-Indicator Panels: A Worked Example from Ghana</h1>
    <div class="sub">A worked example from Ghana using WHO Global Health Observatory and World Bank data</div>
    <div class="auth">Valentine Golden Ghanem · Ghana COCOBOD Cocoa Clinic, Accra, Ghana · ORCID 0009-0002-8332-0220</div>
  </div>

  <div class="hook">Only 1 of 21 national indicators matched a uniform ARIMA(1,1,1) order — order selection is not a formality, and a decisive currency-crisis structural break moved the malaria forecast further than order selection did.</div>

  <div class="bignums">
    <div class="bn"><div class="v">6</div><div class="l">Documented corrections</div><div class="s">Source-provenance pitfalls fixed (Table 1)</div></div>
    <div class="bn"><div class="v">{u5mr_row['arima_2030']:.1f}</div><div class="l">Under-5 mortality, 2030</div><div class="s">per 1,000 · SDG target 25</div></div>
    <div class="bn"><div class="v">1 of 21</div><div class="l">Uniform order matched</div><div class="s">{n_near_tie} of 21 were near-ties</div></div>
    <div class="bn"><div class="v">{n_break_decisive_total}</div><div class="l">Decisive structural breaks</div><div class="s">of {n_break_testable_total} testable checks (Table 5)</div></div>
  </div>

  <div class="body">
    <div class="col">
      <div class="block"><h2><span class="n">1</span>Background</h2>
        <p>Public-domain WHO Global Health Observatory (GHO) and World Bank exports are the default empirical basis for national health-indicator forecasting, but these files carry undocumented structural pitfalls that silently corrupt an analysis if uncorrected, and forecasting choices — method, model order, fitting scale — are typically made ad hoc and per-indicator with no shared, reproducible protocol. Existing Ghana-specific forecasting work is disease- or indicator-specific, each selecting its own method and order independently without a protocol another analyst could reuse.</p></div>
      <div class="block"><h2><span class="n">2</span>Methods</h2>
        <p>A national indicator panel (21 forecastable series of 25 assembled, from 9 public-domain WHO/World Bank sources, individual series ranging 22–92 years) was built and audited for source-provenance pitfalls. LSTM neural networks were evaluated against classical methods (exponential smoothing, ARIMA) via multi-seed, multi-architecture walk-forward validation on two representative series; each series' ARIMA order was then selected by an AICc grid search rather than applied uniformly, and a structural-break sensitivity test was run for the 2020 COVID-19 and 2022 Ghana currency-crisis candidate breaks.</p></div>
      <div class="block"><h2><span class="n">3</span>Order-selection sensitivity</h2>
        <p>AICc difference vs. a uniform ARIMA(1,1,1), all 21 series. Order mismatch was not concentrated among the shortest series — under-five mortality (n=92, the longest series) shows the largest correction.</p>
        <div class="chart">{MARGIN_SVG.replace('width="720" height="460"', 'width="100%" height="380"').replace('viewBox="0 0 720 460"', 'viewBox="0 0 720 460" preserveAspectRatio="xMidYMid meet"')}</div>
      </div>
    </div>
    <div class="col">
      <div class="block"><h2><span class="n">4</span>National forecast trends</h2>
        <p>Historical trend (solid) and 2030 ARIMA point forecast (dashed) for three headline indicators.</p>
        <div class="chart">{TREND_SVG.replace('width="720" height="230"', 'width="100%" height="230"').replace('viewBox="0 0 720 230"', 'viewBox="0 0 720 230" preserveAspectRatio="xMidYMid meet"')}</div>
      </div>
      <div class="block"><h2><span class="n">5</span>Key results</h2>
        <p><b>Under-five mortality</b> is projected to decline to {u5mr_row['arima_2030']:.1f} per 1,000 live births by 2030 (95% CI {u5mr_row['arima_ci_low']:.1f}–{u5mr_row['arima_ci_high']:.1f}), narrowly missing the SDG 3.2 target of 25.</p>
        <p><b>Malaria incidence</b>: a naive fixed-order ARIMA(1,1,1) fit on the raw scale disagreed sharply with an equivalent exponential-smoothing fit ({malaria_gap_naive_pct:.0f}% gap, {_arima_raw_111:.1f} vs. {_ets_raw:.1f}). Fitting on the log scale -- this paper's protocol for non-negative-bounded series -- closed most of that gap on its own ({malaria_gap_logscale_fixed_pct:.1f}% gap, still at the fixed order); the series' own AICc-selected order, added on top of the log-scale fit, left a smaller but non-trivial {malaria_gap_final_pct:.1f}% gap ({malaria_row['arima_2030']:.1f} vs. {malaria_row['ets_2030']:.1f}, final production forecast). Fitting scale did almost all of the work in closing that gap. A decisive 2022 currency-crisis structural break shifts this series' forecast by a further {sb_malaria['currency_2022_pct_change_2030']:+.1f}%, a larger effect than the order-selection correction (Table 5).</p>
        <p><b>Classical methods beat LSTM</b> on both series tested in walk-forward validation (MAPE 0.18–0.29% for ETS/ARIMA vs. 2.3–14.1% for LSTM); LSTM was excluded from the forecasting roster.</p>
        <p><b>Life expectancy</b>: WHO-GHO projects a decline to 64.8 years by 2030 while the independently-sourced World Bank series projects a small increase to 67.6 years; a decisive structural break is found for the World Bank series at both 2020 and 2022, so this divergence is plausibly break-driven in part, not a settled two-source disagreement.</p></div>
      <div class="block"><h2><span class="n">6</span>Selected forecasts (full 21-series data underlying manuscript Figure 3)</h2>
        <table>
          <thead><tr><th>Indicator</th><th>Last value</th><th>ARIMA 2030</th><th>ETS 2030</th><th>Conf.</th></tr></thead>
          <tbody>{POSTER_TABLE_ROWS}</tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="limBox">
    <h2>Limitations</h2>
    <p>Ecological analysis throughout; no individual-level data. LSTM-vs-classical validation tested on only 2 of 21 series. {n_low} of 21 series are low-confidence ({low_n_min}–{low_n_max} years). Structural-break tests were run for all testable series, but most had only 2–5 post-break observations — genuinely underpowered for reliably detecting a level shift, so decisive findings (malaria, World Bank life expectancy) should be read as suggestive, not confirmatory. Routine surveillance completeness in Ghana varies sharply by disease domain in facility-level audits, lowest for malaria (~25% in some years) -- bounding the malaria forecast's external validity most acutely. Findings are specific to Ghana.</p>
  </div>

  <div class="takeaway">
    <h2>What it means</h2>
    <p>The contribution is a reusable, documented workflow and a named set of source-specific pitfalls, not novelty in order selection itself. Researchers reproducing national-indicator forecasts from these sources can adopt the workflow directly; the Ghana-specific forecasts illustrate it and are not offered as planning inputs.</p>
  </div>

  <div class="pf">
    <div><b>Data:</b> WHO Global Health Observatory / Global Health Estimates; World Bank World Development Indicators (public-domain, aggregate, de-identified — no ethics approval required) · <b>Methods:</b> AICc order selection · walk-forward LSTM-vs-classical validation · structural-break sensitivity · STROBE<br/><b>No competing interests. No funding declared.</b><br/><b>Repo:</b> github.com/valentineghanem-bit/disease-burden-forecasting-ghana</div>
    <div class="qr">{QR_SVG}</div>
  </div>
</div>
</body>
</html>
"""

with open(ROOT + r"\poster\Ghana_BurdenForecasting2030_Poster.html", "w", encoding="utf-8") as f:
    f.write(POSTER_HTML)
print(f"Poster written: {len(POSTER_HTML)/1024:.1f} KB")
